export const MAP = `__SECRET_MAP`

export const MARKER = `__SECRET_MARKER`

export const MARKER_WITH_LABEL = `__SECRET_MARKER_WITH_LABEL`

export const RECTANGLE = `__SECRET_RECTANGLE`

export const POLYLINE = `__SECRET_POLYLINE`

export const POLYLINEOPTIONS = `__SECRET_POLYLINEOPTIONS`

export const ICONSEQUENCE = `__SECRET_ICONSEQUENCE`

export const POLYGON = `__SECRET_POLYGON`

export const CIRCLE = `__SECRET_CIRCLE`

export const KML_LAYER = `__SECRET_KML_LAYER`

export const DIRECTIONS_RENDERER = `__SECRET_DIRECTIONS_RENDERER`

export const AUTOCOMPLETE = `__SECRET_AUTOCOMPLETE`

export const HEATMAP_LAYER = `__SECRET_HEATMAP_LAYER`

export const FUSION_TABLES_LAYER = `__SECRET_FUSION_TABLES_LAYER`

export const IMAGEMAPTYPE = `__SECRET_IMAGEMAPTYPE`

export const STREETVIEW_COVERAGE_LAYER = `__SECRET_STREETVIEW_COVERAGE_LAYER`

export const STREETVIEW_SERVICE = `__SECRET_STREETVIEW_SERVICE`

export const ANCHOR = `__SECRET_ANCHOR`

export const INFO_WINDOW = `__SECRET_INFO_WINDOW`

export const OVERLAY_VIEW = `__SECRET_OVERLAY_VIEW`

export const GROUND_LAYER = `__SECRET_GROUND_LAYER`

export const DRAWING_MANAGER = `__SECRET_DRAWING_MANAGER`

export const SEARCH_BOX = `__SECRET_SEARCH_BOX`

export const STANDALONE_SEARCH_BOX = `__SECRET_STANDALONE_SEARCH_BOX`

export const MARKER_CLUSTERER = `__SECRET_MARKER_CLUSTERER`

export const INFO_BOX = `__SECRET_INFO_BOX`

export const TRAFFIC_LAYER = `__SECRET_TRAFFIC_LAYER`

export const STREET_VIEW_PANORAMA = `__SECRET_STREET_VIEW_PANORAMA`

export const BICYCLING_LAYER = `__SECRET_BICYCLING_LAYER`
